### ISSUE TITLE
FYI, Marathon is spelt incorrectly as "Marthon" in the config parser and examples

### ISSUE THREAD

**Issue by dnwe** [ContainX/beethoven#1]
https://github.com/ContainX/beethoven/search?utf8=%E2%9C%93&q=marthon

**Comment by gondor** [comment]
Thanks @dnwe , I have been doing some refactors to support multiple scheduler types including Docker Swarm.  I have deprecated (will still work) the old misspelling and at part of this refactor put schedulers in there own namespace in the config, for example : `marathon: { }`.  This addressed the spelling and future releases will remove the old misspelling

**Comment by dnwe** [comment]
:+1
